// ─────────────────────────────────────────────────────────────────────────────
// Ultima – Product Catalog Data
// Single source of truth for all products, classes, books, and chapters
// ─────────────────────────────────────────────────────────────────────────────

// ── Preparation Products ──────────────────────────────────────────────────────
export const PREP_PRODUCTS = [
  {
    id: "class-10-prep",
    title: "Class 10 Preparation",
    subtitle: "NCERT · Board Focus",
    description: "Complete chapter-wise practice, MCQs, and mock tests aligned to the Class 10 CBSE curriculum.",
    icon: "🏫",
    accentColor: "#2563eb",
    bgColor: "#eff6ff",
    borderColor: "#bfdbfe",
    tags: ["Science", "Maths", "Social", "English"],
    href: "/products/books/class-10",
    category: "ncert",
    stats: { subjects: 6, questions: "1,200+", tests: 24 },
  },
  {
    id: "class-11-prep",
    title: "Class 11 Preparation",
    subtitle: "NCERT · Foundation",
    description: "Build strong fundamentals in Physics, Chemistry and Maths for Class 11 with chapter-level precision.",
    icon: "📗",
    accentColor: "#0891b2",
    bgColor: "#ecfeff",
    borderColor: "#a5f3fc",
    tags: ["Physics", "Chemistry", "Maths", "Biology"],
    href: "/products/books/class-11",
    category: "ncert",
    stats: { subjects: 7, questions: "1,800+", tests: 32 },
  },
  {
    id: "class-12-prep",
    title: "Class 12 Preparation",
    subtitle: "NCERT · Advanced",
    description: "Master Class 12 concepts with advanced practice sets, board-pattern tests and formula sheets.",
    icon: "🎓",
    accentColor: "#7c3aed",
    bgColor: "#f5f3ff",
    borderColor: "#ddd6fe",
    tags: ["Physics", "Chemistry", "Maths", "Biology"],
    href: "/products/books/class-12",
    category: "ncert",
    stats: { subjects: 7, questions: "2,200+", tests: 40 },
  },
  {
    id: "jee-prep",
    title: "JEE Preparation",
    subtitle: "IIT JEE · Main & Advanced",
    description: "Rank-oriented preparation with advanced problem sets, full syllabus mocks, and performance analytics.",
    icon: "⚙️",
    accentColor: "#dc2626",
    bgColor: "#fff5f5",
    borderColor: "#fecaca",
    tags: ["Advanced Practice", "Mock Tests", "Rank Tracking"],
    href: "/products/competitive/jee",
    category: "competitive",
    stats: { subjects: 3, questions: "5,000+", tests: 60 },
  },
  {
    id: "neet-prep",
    title: "NEET Preparation",
    subtitle: "Medical Entrance",
    description: "Biology-focused preparation with NTA-style mocks, analytics, and targeted weak-area improvement.",
    icon: "🩺",
    accentColor: "#059669",
    bgColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    tags: ["Biology Focus", "Mock Simulation", "Weak-area Analysis"],
    href: "/products/competitive/neet",
    category: "competitive",
    stats: { subjects: 4, questions: "4,500+", tests: 50 },
  },
  {
    id: "gate-prep",
    title: "GATE Preparation",
    subtitle: "Engineering · PSU",
    description: "Concept-first technical preparation with subject-wise practice, revision flow, and previous year papers.",
    icon: "🔬",
    accentColor: "#d97706",
    bgColor: "#fffbeb",
    borderColor: "#fde68a",
    tags: ["Subject-wise Prep", "Concept Reinforcement", "Revision Flow"],
    href: "/products/competitive/gate",
    category: "competitive",
    stats: { subjects: 10, questions: "3,800+", tests: 45 },
  },
];

// ── Class → Books Mapping ─────────────────────────────────────────────────────
export const CLASS_CATALOG = {
  "class-10": {
    slug: "class-10",
    title: "Class 10",
    label: "CBSE Class 10",
    description: "Chapter-wise NCERT practice for all Class 10 subjects — science, maths, and more.",
    icon: "🏫",
    books: [
      { slug: "ncert-physics-class-10", title: "NCERT Physics", subtitle: "Class 10 · Science", description: "Light, electricity, magnetism and more from NCERT Class 10 Science.", subject: "Physics", chapters: 5, questions: 96, theme: "themeNavy", emoji: "⚡" },
      { slug: "ncert-chemistry-class-10", title: "NCERT Chemistry", subtitle: "Class 10 · Science", description: "Chemical reactions, acids, metals, carbon compounds from NCERT.", subject: "Chemistry", chapters: 5, questions: 88, theme: "themeAmber", emoji: "🧪" },
      { slug: "ncert-biology-class-10", title: "NCERT Biology", subtitle: "Class 10 · Science", description: "Life processes, reproduction, heredity, environment from NCERT.", subject: "Biology", chapters: 6, questions: 92, theme: "themeForest", emoji: "🌿" },
      { slug: "ncert-maths-class-10", title: "NCERT Mathematics", subtitle: "Class 10 · Maths", description: "Real numbers, polynomials, triangles, trigonometry and statistics.", subject: "Mathematics", chapters: 15, questions: 140, theme: "themeIndigo", emoji: "📐" },
    ],
  },
  "class-11": {
    slug: "class-11",
    title: "Class 11",
    label: "CBSE Class 11",
    description: "Foundation-level NCERT content for Class 11 — the gateway to competitive exam readiness.",
    icon: "📗",
    books: [
      { slug: "ncert-physics-class-11", title: "NCERT Physics", subtitle: "Class 11 · Core", description: "Units, kinematics, laws of motion, work, gravitation and thermodynamics.", subject: "Physics", chapters: 15, questions: 124, theme: "themeNavy", emoji: "⚡" },
      { slug: "ncert-chemistry-class-11", title: "NCERT Chemistry", subtitle: "Class 11 · Core", description: "Atomic structure, bonding, states of matter, thermodynamics and equilibrium.", subject: "Chemistry", chapters: 14, questions: 118, theme: "themeAmber", emoji: "🧪" },
      { slug: "ncert-maths-class-11", title: "NCERT Mathematics", subtitle: "Class 11 · Core", description: "Sets, relations, trigonometry, algebra, coordinate geometry and calculus.", subject: "Mathematics", chapters: 16, questions: 132, theme: "themeIndigo", emoji: "📐" },
      { slug: "ncert-biology-class-11", title: "NCERT Biology", subtitle: "Class 11 · Core", description: "Cell biology, plant and animal kingdom, morphology and physiology.", subject: "Biology", chapters: 22, questions: 110, theme: "themeEmerald", emoji: "🌱" },
    ],
  },
  "class-12": {
    slug: "class-12",
    title: "Class 12",
    label: "CBSE Class 12",
    description: "Advanced NCERT preparation for Class 12 — board-critical and competitive exam aligned.",
    icon: "🎓",
    books: [
      { slug: "ncert-physics-class-12", title: "NCERT Physics", subtitle: "Class 12 · Advanced", description: "Electrostatics, current, magnetism, optics, dual nature and modern physics.", subject: "Physics", chapters: 15, questions: 138, theme: "themeCrimson", emoji: "🚀" },
      { slug: "ncert-chemistry-class-12", title: "NCERT Chemistry", subtitle: "Class 12 · Advanced", description: "Solutions, electrochemistry, coordination compounds and biomolecules.", subject: "Chemistry", chapters: 16, questions: 126, theme: "themeAmber", emoji: "🧪" },
      { slug: "ncert-biology-class-12", title: "NCERT Biology", subtitle: "Class 12 · Advanced", description: "Reproduction, genetics, evolution, human health and ecology.", subject: "Biology", chapters: 16, questions: 141, theme: "themeEmerald", emoji: "🌱" },
      { slug: "ncert-maths-class-12", title: "NCERT Mathematics", subtitle: "Class 12 · Advanced", description: "Relations, matrices, calculus, vectors, 3D geometry and probability.", subject: "Mathematics", chapters: 13, questions: 155, theme: "themeIndigo", emoji: "📐" },
    ],
  },
};

// ── Book → Chapters Mapping ───────────────────────────────────────────────────
export const BOOK_CHAPTERS = {

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CLASS 10 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  "ncert-physics-class-10": {
    slug: "ncert-physics-class-10",
    title: "NCERT Physics",
    classLabel: "Class 10",
    subject: "Physics",
    classSlug: "class-10",
    theme: "themeNavy",
    emoji: "⚡",
    description: "Class 10 Physics — light, electricity, magnetism and the human eye with chapter-level practice.",
    stats: { chapters: 5, questions: 96, tests: 5 },
    chapters: [
      { id: "light-reflection", number: 1, title: "Light – Reflection and Refraction", description: "Laws of reflection, spherical mirrors, refraction, lens formula.", duration: "~45 min", questionCount: 20 },
      { id: "human-eye", number: 2, title: "The Human Eye and the Colourful World", description: "Structure of eye, defects of vision, atmospheric refraction, dispersion.", duration: "~40 min", questionCount: 18 },
      { id: "electricity", number: 3, title: "Electricity", description: "Ohm's law, resistance, series/parallel circuits, heating effect.", duration: "~55 min", questionCount: 22 },
      { id: "magnetic-effects", number: 4, title: "Magnetic Effects of Electric Current", description: "Magnetic field, electromagnetic induction, electric motor and generator.", duration: "~48 min", questionCount: 20 },
      { id: "sources-of-energy", number: 5, title: "Sources of Energy", description: "Conventional and non-conventional sources, solar energy, nuclear energy.", duration: "~35 min", questionCount: 16 },
    ],
  },

  "ncert-chemistry-class-10": {
    slug: "ncert-chemistry-class-10",
    title: "NCERT Chemistry",
    classLabel: "Class 10",
    subject: "Chemistry",
    classSlug: "class-10",
    theme: "themeAmber",
    emoji: "🧪",
    description: "Class 10 Chemistry — chemical reactions, acids, metals, and carbon compounds chapter by chapter.",
    stats: { chapters: 5, questions: 88, tests: 5 },
    chapters: [
      { id: "chemical-reactions", number: 1, title: "Chemical Reactions and Equations", description: "Balancing equations, types of reactions, oxidation and reduction.", duration: "~42 min", questionCount: 18 },
      { id: "acids-bases-salts", number: 2, title: "Acids, Bases and Salts", description: "Properties, pH scale, neutralisation, salts and their uses.", duration: "~45 min", questionCount: 20 },
      { id: "metals-nonmetals", number: 3, title: "Metals and Non-metals", description: "Physical and chemical properties, reactivity series, corrosion.", duration: "~48 min", questionCount: 18 },
      { id: "carbon-compounds", number: 4, title: "Carbon and its Compounds", description: "Covalent bonding, homologous series, soaps and detergents.", duration: "~50 min", questionCount: 20 },
      { id: "periodic-classification", number: 5, title: "Periodic Classification of Elements", description: "Döbereiner, Newlands, Mendeleev and the Modern periodic table.", duration: "~38 min", questionCount: 12 },
    ],
  },

  "ncert-biology-class-10": {
    slug: "ncert-biology-class-10",
    title: "NCERT Biology",
    classLabel: "Class 10",
    subject: "Biology",
    classSlug: "class-10",
    theme: "themeForest",
    emoji: "🌿",
    description: "Class 10 Biology — life processes, reproduction, heredity, and our environment.",
    stats: { chapters: 6, questions: 92, tests: 6 },
    chapters: [
      { id: "life-processes", number: 1, title: "Life Processes", description: "Nutrition, respiration, transportation and excretion in plants and animals.", duration: "~50 min", questionCount: 18 },
      { id: "control-coordination", number: 2, title: "Control and Coordination", description: "Nervous system, reflex actions, hormones in plants and animals.", duration: "~45 min", questionCount: 16 },
      { id: "reproduction", number: 3, title: "How do Organisms Reproduce?", description: "Asexual and sexual reproduction in plants, animals and humans.", duration: "~48 min", questionCount: 16 },
      { id: "heredity-evolution", number: 4, title: "Heredity and Evolution", description: "Mendel's laws, sex determination, evolution and natural selection.", duration: "~50 min", questionCount: 18 },
      { id: "our-environment", number: 5, title: "Our Environment", description: "Ecosystems, food chains, ozone layer, waste management.", duration: "~38 min", questionCount: 14 },
      { id: "natural-resources", number: 6, title: "Management of Natural Resources", description: "Conservation of forests, water, coal, petroleum and sustainable development.", duration: "~35 min", questionCount: 10 },
    ],
  },

  "ncert-maths-class-10": {
    slug: "ncert-maths-class-10",
    title: "NCERT Mathematics",
    classLabel: "Class 10",
    subject: "Mathematics",
    classSlug: "class-10",
    theme: "themeIndigo",
    emoji: "📐",
    description: "Class 10 Maths — real numbers, polynomials, quadratics, geometry, trigonometry and statistics.",
    stats: { chapters: 15, questions: 140, tests: 15 },
    chapters: [
      { id: "real-numbers", number: 1, title: "Real Numbers", description: "Euclid's division lemma, fundamental theorem of arithmetic, irrational numbers.", duration: "~40 min", questionCount: 10 },
      { id: "polynomials", number: 2, title: "Polynomials", description: "Zeros of a polynomial, relationship between zeros and coefficients.", duration: "~38 min", questionCount: 8 },
      { id: "linear-equations", number: 3, title: "Pair of Linear Equations in Two Variables", description: "Graphical and algebraic methods, substitution, elimination.", duration: "~50 min", questionCount: 12 },
      { id: "quadratic-equations", number: 4, title: "Quadratic Equations", description: "Standard form, factorisation, completing the square, discriminant.", duration: "~48 min", questionCount: 10 },
      { id: "arithmetic-progressions", number: 5, title: "Arithmetic Progressions", description: "nth term, sum of first n terms, applications.", duration: "~42 min", questionCount: 10 },
      { id: "triangles", number: 6, title: "Triangles", description: "Similarity, Basic Proportionality Theorem, Pythagoras theorem.", duration: "~52 min", questionCount: 12 },
      { id: "coordinate-geometry", number: 7, title: "Coordinate Geometry", description: "Distance formula, section formula, area of a triangle.", duration: "~42 min", questionCount: 10 },
      { id: "trigonometry-intro", number: 8, title: "Introduction to Trigonometry", description: "Ratios, identities, values of standard angles.", duration: "~45 min", questionCount: 10 },
      { id: "trigonometry-applications", number: 9, title: "Some Applications of Trigonometry", description: "Heights and distances, angles of elevation and depression.", duration: "~40 min", questionCount: 8 },
      { id: "circles", number: 10, title: "Circles", description: "Tangent to a circle, number of tangents from a point.", duration: "~38 min", questionCount: 8 },
      { id: "constructions", number: 11, title: "Constructions", description: "Division of line segment, tangents to a circle.", duration: "~30 min", questionCount: 6 },
      { id: "areas-circle", number: 12, title: "Areas Related to Circles", description: "Perimeter and area of a circle, sector, segment.", duration: "~40 min", questionCount: 10 },
      { id: "surface-volumes", number: 13, title: "Surface Areas and Volumes", description: "Combination of solids, conversion of solids, frustum of a cone.", duration: "~48 min", questionCount: 12 },
      { id: "statistics", number: 14, title: "Statistics", description: "Mean, median, mode for grouped data, cumulative frequency.", duration: "~45 min", questionCount: 12 },
      { id: "probability", number: 15, title: "Probability", description: "Classical definition, simple problems on single events.", duration: "~35 min", questionCount: 12 },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CLASS 11 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  "ncert-physics-class-11": {
    slug: "ncert-physics-class-11",
    title: "NCERT Physics",
    classLabel: "Class 11",
    subject: "Physics",
    classSlug: "class-11",
    theme: "themeNavy",
    emoji: "⚡",
    description: "Class 11 Physics — from units and kinematics to thermodynamics and oscillations.",
    stats: { chapters: 15, questions: 124, tests: 15 },
    chapters: [
      { id: "units-measurements", number: 1, title: "Units and Measurements", description: "SI units, significant figures, dimensions and error analysis.", duration: "~40 min", questionCount: 8 },
      { id: "motion-straight-line", number: 2, title: "Motion in a Straight Line", description: "Distance, displacement, velocity, acceleration, equations of motion.", duration: "~45 min", questionCount: 9 },
      { id: "motion-plane", number: 3, title: "Motion in a Plane", description: "Vectors, projectile motion, circular motion, relative velocity.", duration: "~50 min", questionCount: 10 },
      { id: "laws-of-motion", number: 4, title: "Laws of Motion", description: "Newton's three laws, inertia, friction, equilibrium of forces.", duration: "~52 min", questionCount: 10 },
      { id: "work-energy", number: 5, title: "Work, Energy and Power", description: "Work-energy theorem, potential energy, conservation, collisions.", duration: "~48 min", questionCount: 9 },
      { id: "system-of-particles", number: 6, title: "System of Particles and Rotational Motion", description: "Centre of mass, torque, angular momentum, moment of inertia.", duration: "~55 min", questionCount: 10 },
      { id: "gravitation-11", number: 7, title: "Gravitation", description: "Kepler's laws, universal gravitation, escape velocity, satellites.", duration: "~45 min", questionCount: 8 },
      { id: "mechanical-solids", number: 8, title: "Mechanical Properties of Solids", description: "Stress, strain, elastic moduli, Hooke's law.", duration: "~38 min", questionCount: 7 },
      { id: "mechanical-fluids", number: 9, title: "Mechanical Properties of Fluids", description: "Pressure, Bernoulli's principle, viscosity, surface tension.", duration: "~45 min", questionCount: 8 },
      { id: "thermal-properties", number: 10, title: "Thermal Properties of Matter", description: "Heat capacity, calorimetry, change of state, heat transfer.", duration: "~42 min", questionCount: 8 },
      { id: "thermodynamics-11", number: 11, title: "Thermodynamics", description: "Zeroth, first and second laws, heat engines, entropy.", duration: "~50 min", questionCount: 9 },
      { id: "kinetic-theory", number: 12, title: "Kinetic Theory", description: "Molecular nature of matter, kinetic theory of gases, specific heats.", duration: "~40 min", questionCount: 8 },
      { id: "oscillations", number: 13, title: "Oscillations", description: "Simple harmonic motion, energy in SHM, damped oscillations.", duration: "~48 min", questionCount: 10 },
      { id: "waves", number: 14, title: "Waves", description: "Transverse and longitudinal waves, standing waves, Doppler effect.", duration: "~50 min", questionCount: 10 },
      { id: "physical-world", number: 15, title: "Physical World", description: "Scope of physics, fundamental forces, nature of physical laws.", duration: "~25 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-chemistry-class-11": {
    slug: "ncert-chemistry-class-11",
    title: "NCERT Chemistry",
    classLabel: "Class 11",
    subject: "Chemistry",
    classSlug: "class-11",
    theme: "themeAmber",
    emoji: "🧪",
    description: "Class 11 Chemistry — atomic structure, bonding, states of matter, thermodynamics and equilibrium.",
    stats: { chapters: 14, questions: 118, tests: 14 },
    chapters: [
      { id: "basic-concepts", number: 1, title: "Some Basic Concepts of Chemistry", description: "Mole concept, stoichiometry, laws of chemical combination.", duration: "~42 min", questionCount: 9 },
      { id: "structure-of-atom", number: 2, title: "Structure of Atom", description: "Atomic models, quantum numbers, orbitals, electronic configuration.", duration: "~50 min", questionCount: 10 },
      { id: "periodic-table-11", number: 3, title: "Classification of Elements and Periodicity", description: "Modern periodic law, trends in properties, blocks of elements.", duration: "~42 min", questionCount: 8 },
      { id: "chemical-bonding", number: 4, title: "Chemical Bonding and Molecular Structure", description: "Ionic, covalent bonding, VSEPR, hybridisation, MO theory.", duration: "~55 min", questionCount: 10 },
      { id: "states-of-matter", number: 5, title: "States of Matter", description: "Gaseous state, gas laws, liquefaction, liquid state.", duration: "~45 min", questionCount: 8 },
      { id: "thermodynamics-chem11", number: 6, title: "Thermodynamics", description: "System, enthalpy, Hess's law, entropy, Gibbs energy.", duration: "~50 min", questionCount: 9 },
      { id: "equilibrium-11", number: 7, title: "Equilibrium", description: "Chemical equilibrium, Le Chatelier's principle, ionic equilibrium.", duration: "~52 min", questionCount: 10 },
      { id: "redox", number: 8, title: "Redox Reactions", description: "Oxidation state, balancing redox equations, electrochemical series.", duration: "~40 min", questionCount: 8 },
      { id: "hydrogen", number: 9, title: "Hydrogen", description: "Position in periodic table, preparation, properties, water.", duration: "~35 min", questionCount: 7 },
      { id: "s-block", number: 10, title: "The s-Block Elements", description: "Alkali and alkaline earth metals, their compounds.", duration: "~40 min", questionCount: 8 },
      { id: "p-block-11", number: 11, title: "The p-Block Elements (Group 13–14)", description: "Boron, carbon families — properties and compounds.", duration: "~42 min", questionCount: 8 },
      { id: "organic-basics", number: 12, title: "Organic Chemistry – Basic Principles", description: "Nomenclature, isomerism, reaction mechanisms, inductive effect.", duration: "~48 min", questionCount: 9 },
      { id: "hydrocarbons", number: 13, title: "Hydrocarbons", description: "Alkanes, alkenes, alkynes, benzene, conformations.", duration: "~50 min", questionCount: 10 },
      { id: "environmental-chem", number: 14, title: "Environmental Chemistry", description: "Atmospheric pollution, water pollution, soil pollution.", duration: "~30 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-maths-class-11": {
    slug: "ncert-maths-class-11",
    title: "NCERT Mathematics",
    classLabel: "Class 11",
    subject: "Mathematics",
    classSlug: "class-11",
    theme: "themeIndigo",
    emoji: "📐",
    description: "Class 11 Maths — sets, relations, trigonometry, algebra, coordinate geometry and calculus intro.",
    stats: { chapters: 16, questions: 132, tests: 16 },
    chapters: [
      { id: "sets", number: 1, title: "Sets", description: "Types of sets, Venn diagrams, operations on sets, De Morgan's laws.", duration: "~40 min", questionCount: 8 },
      { id: "relations-functions-11", number: 2, title: "Relations and Functions", description: "Ordered pairs, Cartesian product, types of functions.", duration: "~42 min", questionCount: 8 },
      { id: "trigonometric-functions", number: 3, title: "Trigonometric Functions", description: "Radian measure, identities, values, graphs of trig functions.", duration: "~52 min", questionCount: 10 },
      { id: "complex-numbers", number: 4, title: "Complex Numbers and Quadratic Equations", description: "Imaginary unit, algebra of complex numbers, Argand plane.", duration: "~45 min", questionCount: 9 },
      { id: "linear-inequalities", number: 5, title: "Linear Inequalities", description: "Algebraic and graphical solutions of linear inequalities.", duration: "~38 min", questionCount: 8 },
      { id: "permutations-combinations", number: 6, title: "Permutations and Combinations", description: "Fundamental principle, nPr, nCr, applications.", duration: "~45 min", questionCount: 9 },
      { id: "binomial-theorem", number: 7, title: "Binomial Theorem", description: "Binomial expansion, general term, middle term.", duration: "~40 min", questionCount: 8 },
      { id: "sequences-series", number: 8, title: "Sequences and Series", description: "AP, GP, AM, GM, sum of special series.", duration: "~48 min", questionCount: 9 },
      { id: "straight-lines", number: 9, title: "Straight Lines", description: "Slope, various forms of equation, distance between lines.", duration: "~45 min", questionCount: 9 },
      { id: "conic-sections", number: 10, title: "Conic Sections", description: "Circle, parabola, ellipse, hyperbola — standard equations.", duration: "~52 min", questionCount: 10 },
      { id: "3d-intro", number: 11, title: "Introduction to Three-Dimensional Geometry", description: "Coordinate axes, distance formula, section formula in 3D.", duration: "~38 min", questionCount: 8 },
      { id: "limits-derivatives", number: 12, title: "Limits and Derivatives", description: "Intuitive idea of limit, algebra of limits, derivatives.", duration: "~50 min", questionCount: 9 },
      { id: "statistics-11", number: 13, title: "Statistics", description: "Measures of dispersion, mean deviation, variance, standard deviation.", duration: "~42 min", questionCount: 8 },
      { id: "probability-11", number: 14, title: "Probability", description: "Random experiment, sample space, events, axiomatic approach.", duration: "~40 min", questionCount: 8 },
      { id: "mathematical-reasoning", number: 15, title: "Mathematical Reasoning", description: "Statements, connectives, validation of statements.", duration: "~30 min", questionCount: 0, comingSoon: true },
      { id: "mathematical-induction", number: 16, title: "Principle of Mathematical Induction", description: "Process of the proof by induction, motivating applications.", duration: "~30 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-biology-class-11": {
    slug: "ncert-biology-class-11",
    title: "NCERT Biology",
    classLabel: "Class 11",
    subject: "Biology",
    classSlug: "class-11",
    theme: "themeEmerald",
    emoji: "🌱",
    description: "Class 11 Biology — cell biology, plant and animal kingdom, morphology and physiology.",
    stats: { chapters: 22, questions: 110, tests: 22 },
    chapters: [
      { id: "living-world", number: 1, title: "The Living World", description: "What is living, taxonomy, systematic and binomial nomenclature.", duration: "~35 min", questionCount: 5 },
      { id: "biological-classification", number: 2, title: "Biological Classification", description: "Five kingdom classification, Monera, Protista, Fungi, Plantae, Animalia.", duration: "~40 min", questionCount: 6 },
      { id: "plant-kingdom", number: 3, title: "Plant Kingdom", description: "Algae, bryophytes, pteridophytes, gymnosperms, angiosperms.", duration: "~45 min", questionCount: 6 },
      { id: "animal-kingdom", number: 4, title: "Animal Kingdom", description: "Basis of classification, different phyla and their characteristics.", duration: "~45 min", questionCount: 6 },
      { id: "morphology-flowering", number: 5, title: "Morphology of Flowering Plants", description: "Root, stem, leaf, flower, fruit, seed — structure and modification.", duration: "~48 min", questionCount: 6 },
      { id: "anatomy-flowering", number: 6, title: "Anatomy of Flowering Plants", description: "Tissue systems, anatomy of root, stem, and leaf.", duration: "~45 min", questionCount: 5 },
      { id: "structural-animals", number: 7, title: "Structural Organisation in Animals", description: "Tissues, organs of earthworm, cockroach and frog.", duration: "~48 min", questionCount: 5 },
      { id: "cell-unit", number: 8, title: "Cell: The Unit of Life", description: "Prokaryotic and eukaryotic cell, cell organelles.", duration: "~50 min", questionCount: 6 },
      { id: "biomolecules-11", number: 9, title: "Biomolecules", description: "Chemical constituents of cell — carbohydrates, proteins, lipids, nucleic acids.", duration: "~48 min", questionCount: 5 },
      { id: "cell-cycle", number: 10, title: "Cell Cycle and Cell Division", description: "Cell cycle, mitosis, meiosis and their significance.", duration: "~45 min", questionCount: 5 },
      { id: "transport-plants", number: 11, title: "Transport in Plants", description: "Means of transport, water potential, transpiration, phloem loading.", duration: "~42 min", questionCount: 5 },
      { id: "mineral-nutrition", number: 12, title: "Mineral Nutrition", description: "Essential mineral elements, mechanism of absorption, nitrogen cycle.", duration: "~38 min", questionCount: 5 },
      { id: "photosynthesis", number: 13, title: "Photosynthesis in Higher Plants", description: "Light reactions, Calvin cycle, photorespiration, C4 pathway.", duration: "~52 min", questionCount: 6 },
      { id: "respiration-plants", number: 14, title: "Respiration in Plants", description: "Glycolysis, fermentation, aerobic respiration, energy relations.", duration: "~48 min", questionCount: 5 },
      { id: "plant-growth", number: 15, title: "Plant Growth and Development", description: "Growth regulators, seed germination, dormancy, vernalisation.", duration: "~40 min", questionCount: 5 },
      { id: "digestion", number: 16, title: "Digestion and Absorption", description: "Human alimentary canal, digestion, absorption and assimilation.", duration: "~45 min", questionCount: 5 },
      { id: "breathing", number: 17, title: "Breathing and Exchange of Gases", description: "Respiratory organs, mechanism of breathing, transport of gases.", duration: "~42 min", questionCount: 5 },
      { id: "body-fluids", number: 18, title: "Body Fluids and Circulation", description: "Blood, lymph, human circulatory system, ECG, disorders.", duration: "~48 min", questionCount: 5 },
      { id: "excretion", number: 19, title: "Excretory Products and their Elimination", description: "Modes of excretion, human excretory system, kidney function.", duration: "~45 min", questionCount: 5 },
      { id: "locomotion", number: 20, title: "Locomotion and Movement", description: "Types of movement, skeletal system, muscle contraction, disorders.", duration: "~45 min", questionCount: 5 },
      { id: "neural-control", number: 21, title: "Neural Control and Coordination", description: "Neuron, reflex arc, human brain, sensory organs.", duration: "~48 min", questionCount: 5 },
      { id: "chemical-coordination", number: 22, title: "Chemical Coordination and Integration", description: "Endocrine glands, hormones and their regulation.", duration: "~40 min", questionCount: 0, comingSoon: true },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CLASS 12 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  "ncert-physics-class-12": {
    slug: "ncert-physics-class-12",
    title: "NCERT Physics",
    classLabel: "Class 12",
    subject: "Physics",
    classSlug: "class-12",
    theme: "themeCrimson",
    emoji: "🚀",
    description: "Complete Class 12 Physics — from electrostatics to semiconductors with chapter-level practice.",
    stats: { chapters: 15, questions: 138, tests: 15 },
    chapters: [
      { id: "electric-charges", number: 1, title: "Electric Charges and Fields", description: "Coulomb's law, electric field, Gauss's theorem and field lines.", duration: "~45 min", questionCount: 12 },
      { id: "electrostatic-potential", number: 2, title: "Electrostatic Potential and Capacitance", description: "Potential energy, capacitors, dielectrics and energy stored.", duration: "~50 min", questionCount: 10 },
      { id: "current-electricity", number: 3, title: "Current Electricity", description: "Ohm's law, drift velocity, Kirchhoff's laws and Wheatstone bridge.", duration: "~55 min", questionCount: 14 },
      { id: "moving-charges", number: 4, title: "Moving Charges and Magnetism", description: "Biot-Savart law, Ampere's law, cyclotron and galvanometers.", duration: "~50 min", questionCount: 11 },
      { id: "magnetism-matter", number: 5, title: "Magnetism and Matter", description: "Bar magnet, Earth's magnetism, dia/para/ferromagnetic materials.", duration: "~40 min", questionCount: 8 },
      { id: "electromagnetic-induction", number: 6, title: "Electromagnetic Induction", description: "Faraday's laws, Lenz's law, motional EMF and inductance.", duration: "~48 min", questionCount: 10 },
      { id: "alternating-current", number: 7, title: "Alternating Current", description: "AC circuits, impedance, resonance, LC oscillations and transformers.", duration: "~52 min", questionCount: 11 },
      { id: "electromagnetic-waves", number: 8, title: "Electromagnetic Waves", description: "Maxwell's equations, EM spectrum, properties of EM waves.", duration: "~35 min", questionCount: 7 },
      { id: "ray-optics", number: 9, title: "Ray Optics and Optical Instruments", description: "Reflection, refraction, lenses, microscope and telescope.", duration: "~60 min", questionCount: 15 },
      { id: "wave-optics", number: 10, title: "Wave Optics", description: "Huygens principle, interference, diffraction and polarisation.", duration: "~48 min", questionCount: 10 },
      { id: "dual-nature", number: 11, title: "Dual Nature of Radiation and Matter", description: "Photoelectric effect, de Broglie wavelength and Davisson-Germer.", duration: "~42 min", questionCount: 9 },
      { id: "atoms", number: 12, title: "Atoms", description: "Rutherford model, Bohr model, atomic spectra and hydrogen.", duration: "~40 min", questionCount: 8 },
      { id: "nuclei", number: 13, title: "Nuclei", description: "Binding energy, radioactivity, nuclear fission and fusion.", duration: "~45 min", questionCount: 8 },
      { id: "semiconductor-devices", number: 14, title: "Semiconductor Electronics", description: "p-n junction, diodes, transistors, logic gates and digital circuits.", duration: "~55 min", questionCount: 15 },
      { id: "communication-systems", number: 15, title: "Communication Systems", description: "Modulation, transmission, bandwidth, antennas and Internet.", duration: "~35 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-chemistry-class-12": {
    slug: "ncert-chemistry-class-12",
    title: "NCERT Chemistry",
    classLabel: "Class 12",
    subject: "Chemistry",
    classSlug: "class-12",
    theme: "themeAmber",
    emoji: "🧪",
    description: "Class 12 Chemistry from solid state to polymers — chapter-wise questions, tests and notes.",
    stats: { chapters: 16, questions: 126, tests: 16 },
    chapters: [
      { id: "solid-state", number: 1, title: "The Solid State", description: "Crystal systems, defects, electrical and magnetic properties.", duration: "~42 min", questionCount: 8 },
      { id: "solutions-ch", number: 2, title: "Solutions", description: "Types, concentration, colligative properties, osmosis.", duration: "~48 min", questionCount: 9 },
      { id: "electrochemistry", number: 3, title: "Electrochemistry", description: "Cell potential, Nernst equation, electrolysis, batteries.", duration: "~50 min", questionCount: 10 },
      { id: "chemical-kinetics", number: 4, title: "Chemical Kinetics", description: "Rate laws, order, activation energy, Arrhenius equation.", duration: "~45 min", questionCount: 9 },
      { id: "surface-chemistry", number: 5, title: "Surface Chemistry", description: "Adsorption, catalysis, colloids and emulsions.", duration: "~38 min", questionCount: 7 },
      { id: "isolation-elements", number: 6, title: "General Principles of Isolation of Elements", description: "Occurrence, extraction, refining of metals.", duration: "~35 min", questionCount: 6 },
      { id: "p-block-12-1", number: 7, title: "The p-Block Elements (Part I)", description: "Groups 15-16: nitrogen family and oxygen family.", duration: "~50 min", questionCount: 9 },
      { id: "p-block-12-2", number: 8, title: "The p-Block Elements (Part II)", description: "Groups 17-18: halogens and noble gases.", duration: "~42 min", questionCount: 8 },
      { id: "d-f-block", number: 9, title: "The d- and f-Block Elements", description: "Transition metals, lanthanides, actinides.", duration: "~48 min", questionCount: 9 },
      { id: "coordination", number: 10, title: "Coordination Compounds", description: "IUPAC nomenclature, isomerism, bonding, CFT.", duration: "~55 min", questionCount: 12 },
      { id: "haloalkanes", number: 11, title: "Haloalkanes and Haloarenes", description: "Preparation, reactions, uses of halogen compounds.", duration: "~45 min", questionCount: 8 },
      { id: "alcohols", number: 12, title: "Alcohols, Phenols and Ethers", description: "Classification, reactions, acidity.", duration: "~48 min", questionCount: 9 },
      { id: "aldehydes", number: 13, title: "Aldehydes, Ketones and Carboxylic Acids", description: "Preparation, reactions, uses.", duration: "~52 min", questionCount: 10 },
      { id: "amines", number: 14, title: "Amines", description: "Classification, preparation, properties of amines.", duration: "~40 min", questionCount: 7 },
      { id: "biomolecules-12", number: 15, title: "Biomolecules", description: "Carbohydrates, proteins, lipids, nucleic acids, vitamins.", duration: "~45 min", questionCount: 8 },
      { id: "polymers", number: 16, title: "Polymers", description: "Classification, preparation, uses of synthetic polymers.", duration: "~35 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-biology-class-12": {
    slug: "ncert-biology-class-12",
    title: "NCERT Biology",
    classLabel: "Class 12",
    subject: "Biology",
    classSlug: "class-12",
    theme: "themeEmerald",
    emoji: "🌱",
    description: "Complete Class 12 Biology — genetics, evolution, ecology, and human health.",
    stats: { chapters: 16, questions: 141, tests: 16 },
    chapters: [
      { id: "sexual-reproduction", number: 1, title: "Sexual Reproduction in Flowering Plants", description: "Flower structure, pollination, fertilisation, seed development.", duration: "~50 min", questionCount: 10 },
      { id: "human-reproduction", number: 2, title: "Human Reproduction", description: "Male and female reproductive systems, gametogenesis, fertilisation.", duration: "~48 min", questionCount: 9 },
      { id: "reproductive-health", number: 3, title: "Reproductive Health", description: "Population control, contraceptives, STIs, MTP.", duration: "~38 min", questionCount: 7 },
      { id: "principles-heredity", number: 4, title: "Principles of Inheritance and Variation", description: "Mendel's laws, dominance, sex determination, chromosomal disorders.", duration: "~55 min", questionCount: 12 },
      { id: "molecular-inheritance", number: 5, title: "Molecular Basis of Inheritance", description: "DNA structure, replication, transcription, translation, gene regulation.", duration: "~60 min", questionCount: 14 },
      { id: "evolution", number: 6, title: "Evolution", description: "Origin of life, Darwin's theory, evidence and speciation.", duration: "~45 min", questionCount: 9 },
      { id: "human-health", number: 7, title: "Human Health and Disease", description: "Immunity, vaccines, allergies, cancer, drugs and alcohol.", duration: "~50 min", questionCount: 10 },
      { id: "food-production", number: 8, title: "Strategies for Enhancement in Food Production", description: "Plant breeding, tissue culture, animal husbandry.", duration: "~40 min", questionCount: 8 },
      { id: "microbes", number: 9, title: "Microbes in Human Welfare", description: "Microbes in food, biogas, sewage, biocontrol.", duration: "~38 min", questionCount: 7 },
      { id: "biotechnology", number: 10, title: "Biotechnology – Principles and Processes", description: "Recombinant DNA, cloning, PCR, electrophoresis.", duration: "~52 min", questionCount: 10 },
      { id: "biotech-applications", number: 11, title: "Biotechnology and its Applications", description: "GM organisms, biopharmaceuticals, gene therapy, bioethics.", duration: "~45 min", questionCount: 9 },
      { id: "organisms-environment", number: 12, title: "Organisms and Populations", description: "Ecology, population attributes, growth, interactions.", duration: "~48 min", questionCount: 9 },
      { id: "ecosystem", number: 13, title: "Ecosystem", description: "Productivity, decomposition, energy flow, ecological pyramids.", duration: "~45 min", questionCount: 9 },
      { id: "biodiversity", number: 14, title: "Biodiversity and Conservation", description: "Types of biodiversity, hotspots, threats, in-situ and ex-situ.", duration: "~42 min", questionCount: 8 },
      { id: "environmental-issues", number: 15, title: "Environmental Issues", description: "Pollution types, greenhouse effect, ozone depletion.", duration: "~40 min", questionCount: 0, comingSoon: true },
    ],
  },

  "ncert-maths-class-12": {
    slug: "ncert-maths-class-12",
    title: "NCERT Mathematics",
    classLabel: "Class 12",
    subject: "Mathematics",
    classSlug: "class-12",
    theme: "themeIndigo",
    emoji: "📐",
    description: "Class 12 Maths — relations, matrices, calculus, vectors, 3D geometry and probability.",
    stats: { chapters: 13, questions: 155, tests: 13 },
    chapters: [
      { id: "relations-functions-12", number: 1, title: "Relations and Functions", description: "Types of relations, functions, composition and invertible functions.", duration: "~45 min", questionCount: 12 },
      { id: "inverse-trig", number: 2, title: "Inverse Trigonometric Functions", description: "Domains, ranges and properties of inverse trig functions.", duration: "~40 min", questionCount: 10 },
      { id: "matrices", number: 3, title: "Matrices", description: "Operations, transpose, symmetric, invertible matrices.", duration: "~50 min", questionCount: 14 },
      { id: "determinants", number: 4, title: "Determinants", description: "Properties, cofactors, applications in area and system of equations.", duration: "~52 min", questionCount: 13 },
      { id: "continuity", number: 5, title: "Continuity and Differentiability", description: "Continuity, chain rule, implicit, logarithmic differentiation.", duration: "~55 min", questionCount: 14 },
      { id: "applications-derivatives", number: 6, title: "Applications of Derivatives", description: "Rate of change, increasing/decreasing, tangents, maxima/minima.", duration: "~55 min", questionCount: 14 },
      { id: "integrals", number: 7, title: "Integrals", description: "Indefinite integrals, substitution, partial fractions, by parts.", duration: "~60 min", questionCount: 16 },
      { id: "applications-integrals", number: 8, title: "Applications of Integrals", description: "Area under curves between lines, circles, parabolas and ellipses.", duration: "~45 min", questionCount: 10 },
      { id: "differential-equations", number: 9, title: "Differential Equations", description: "Order, degree, formation, variable separable, linear DEs.", duration: "~52 min", questionCount: 13 },
      { id: "vectors", number: 10, title: "Vector Algebra", description: "Types, operations, scalar and vector products.", duration: "~48 min", questionCount: 12 },
      { id: "3d-geometry", number: 11, title: "Three Dimensional Geometry", description: "Direction cosines, lines, planes in 3D space.", duration: "~50 min", questionCount: 12 },
      { id: "linear-programming", number: 12, title: "Linear Programming", description: "Feasible region, objective function, corner point method.", duration: "~40 min", questionCount: 10 },
      { id: "probability-12", number: 13, title: "Probability", description: "Conditional probability, Bayes' theorem, random variables, distributions.", duration: "~55 min", questionCount: 15 },
    ],
  },
};
